name: AI 프로덕션 서버 EC2 배포

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: 배포 작업
    runs-on: ubuntu-latest

    env:
      # 프로젝트
      PROJECT_NAME: ai-rena-ai
      # AWS 관련
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
      # fastapi 관련
      ENV_CONTENT: ${{ secrets.ENV_CONTENT }}

    steps:
      - name: EC2에 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          debug: true
          script: |
            git checkout main
            git pull
            echo "$ENV_CONTENT" | base64 -d > .env
            docker stop ${{ env.PROJECT_NAME }}
            docker rm ${{ env.PROJECT_NAME }}
            docker build -t ${{ env.PROJECT_NAME }}:lastest .
            docker run -d --name ${{ env.PROJECT_NAME }} -p 8000:8000 ${{ env.PROJECT_NAME }}:lastest 
            docker image prune -af
            EOF
